// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: orders.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrdersStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersStatus) Reset() {
	*x = OrdersStatus{}
	mi := &file_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersStatus) ProtoMessage() {}

func (x *OrdersStatus) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersStatus.ProtoReflect.Descriptor instead.
func (*OrdersStatus) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{0}
}

func (x *OrdersStatus) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrdersStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderStatusPaid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StatusPaid    string                 `protobuf:"bytes,2,opt,name=status_paid,json=statusPaid,proto3" json:"status_paid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusPaid) Reset() {
	*x = OrderStatusPaid{}
	mi := &file_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusPaid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusPaid) ProtoMessage() {}

func (x *OrderStatusPaid) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusPaid.ProtoReflect.Descriptor instead.
func (*OrderStatusPaid) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{1}
}

func (x *OrderStatusPaid) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderStatusPaid) GetStatusPaid() string {
	if x != nil {
		return x.StatusPaid
	}
	return ""
}

type OrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusResponse) Reset() {
	*x = OrderStatusResponse{}
	mi := &file_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusResponse) ProtoMessage() {}

func (x *OrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_orders_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatusResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

func (x *OrderStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderStatusResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_orders_proto protoreflect.FileDescriptor

const file_orders_proto_rawDesc = "" +
	"\n" +
	"\forders.proto\x12\x06orders\"6\n" +
	"\fOrdersStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"B\n" +
	"\x0fOrderStatusPaid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vstatus_paid\x18\x02 \x01(\tR\n" +
	"statusPaid\"Y\n" +
	"\x13OrderStatusResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id2\xa5\x01\n" +
	"\fOrderService\x12F\n" +
	"\x11ChangeOrderStatus\x12\x14.orders.OrdersStatus\x1a\x1b.orders.OrderStatusResponse\x12M\n" +
	"\x15ChangeOrderStatusPaid\x12\x17.orders.OrderStatusPaid\x1a\x1b.orders.OrderStatusResponseB5Z3github.com/AndreyLebedev1998/shop-gRPC-orders/orderb\x06proto3"

var (
	file_orders_proto_rawDescOnce sync.Once
	file_orders_proto_rawDescData []byte
)

func file_orders_proto_rawDescGZIP() []byte {
	file_orders_proto_rawDescOnce.Do(func() {
		file_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)))
	})
	return file_orders_proto_rawDescData
}

var file_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orders_proto_goTypes = []any{
	(*OrdersStatus)(nil),        // 0: orders.OrdersStatus
	(*OrderStatusPaid)(nil),     // 1: orders.OrderStatusPaid
	(*OrderStatusResponse)(nil), // 2: orders.OrderStatusResponse
}
var file_orders_proto_depIdxs = []int32{
	0, // 0: orders.OrderService.ChangeOrderStatus:input_type -> orders.OrdersStatus
	1, // 1: orders.OrderService.ChangeOrderStatusPaid:input_type -> orders.OrderStatusPaid
	2, // 2: orders.OrderService.ChangeOrderStatus:output_type -> orders.OrderStatusResponse
	2, // 3: orders.OrderService.ChangeOrderStatusPaid:output_type -> orders.OrderStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_proto_init() }
func file_orders_proto_init() {
	if File_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_proto_rawDesc), len(file_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_proto_goTypes,
		DependencyIndexes: file_orders_proto_depIdxs,
		MessageInfos:      file_orders_proto_msgTypes,
	}.Build()
	File_orders_proto = out.File
	file_orders_proto_goTypes = nil
	file_orders_proto_depIdxs = nil
}
